defmodule Tradewinds.Repo do
  @moduledoc """
  This module defines the Repo used by Tradewinds.  This was generated by Phoenix.
"""
  use Ecto.Repo,
    otp_app: :tradewinds,
    adapter: Ecto.Adapters.Postgres
end
