FROM debian:buster

RUN apt update && apt install --yes wget gnupg2 curl unzip
RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
RUN dpkg -i erlang-solutions_1.0_all.deb
RUN apt update && apt install --yes postgresql postgresql-contrib erlang elixir git
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN mix local.hex --force
RUN mix local.rebar --force
